.TH "htpasswd-caudium" "1" "1.3.15" "The Caudium Group" "The Caudium WebServer"
.SH "NAME"
.LP 
htpasswd\-caudium \- sets the .htaccess password for the specified user
.SH "SYNTAX"
.LP 
htpasswd\-caudium [\fI\-c\fP] <\fIpasswordfile\fP> <\fIusername\fP>

.SH "DESCRIPTION"
.LP 
This sets the specified user's password in the specified file. The file is created if it doesn't exist and the \fB\-c\fR flag is passed to the program..br 
This utility is \fBnot\fR compatible with the apache webserver utility of the same name.
.SH "OPTIONS"
.LP 
.TP 
\fB\-c\fR
Create the password file if it doesn't exist.
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.SH "AUTHORS"
.LP 
The Caudium Group \-\- http://caudium.net/
