.\" $Id$
.TH "ultrasum" "1" "1.0.35" "The Caudium Group" "Utilities"
.SH "NAME"
.LP 
ultrasum \- generates summary files for the UltraLog module
.SH "SYNTAX"
.LP 
ultrasum <\fIpath_to_config_file\fP>

.SH "DESCRIPTION"
.LP 
This is a frontend script that runs a Pike application that generates the
summary files for the Caudium Log Analyzer module \- UltraLog..br 
The only parameter expected is the path to the UltraLog config file described 
briefly in the UltraLog README file.

.SH "EXAMPLES"
.LP 
You can find an example of the config file in the UltraLog documentation
directory.
.SH "AUTHORS"
.LP 
David Hedbor <david@caudium.net>
