.TH "htpasswd-caudium" "1" "1.2.23" "The Caudium Group" "The Caudium WebServer"
.SH "NOM"
.LP 
htpasswd\-caudium \- encrypte le mot de passe .htaccess pour l'utilisateur spécifié
.SH "SYNTAXE"
.LP 
htpasswd\-caudium [\fI\-c\fP] <\fIfichier\fP> <\fIutilisateur\fP>

.SH "DESCRIPTION"
.LP 
Ce programme encrypte un mot de passe pour un utilisateur dans un fichier donné.
Si le fichier n'existe pas et que l'option \fB\-c\fR est passée, le fichier est créé. 
Ce programme n'est \fBpas\fR compatible avec le programme htpasswd du serveur Apache.
.SH "OPTIONS"
.LP 
.TP 
\fB\-c\fR
Crée le fichier de mot de passe s'il n'éxiste pas.
.TP 
\fB\-\-help\fR
Affiche un texte d'aide et quitte.
.TP 
\fB\-\-version\fR
Affiche la version et quitte.
.SH "AUTEURS"
.LP 
The Caudium Group \-\- http://caudium.net/
