#ifndef FCGI_CONFIG_H
#define FCGI_CONFIG_H
@TOP@

@BOTTOM@

#undef HAVE_FPOS 
#undef HAVE_SOCKADDR_UN_SUN_LEN 
#undef HAVE_SYS_SELECT_H 
#undef NO_FD_SET 
#undef USE_GCC_CONSTRUCTOR_ATTR 
#undef USE_LOCKING 
#undef WITH_ASSERT 
#undef WITH_DEBUG 
#undef WITH_TEST 
#endif
