.TH "pixsl" "1" "1.3.15" "The Caudium Group" "Caudium WebServer"
.SH "NAME"
.LP 
pixsl \- convert a document using the specified XSLT stylesheet.
.SH "SYNTAX"
.LP 
pixsl <\fIstylesheet\fP> [\fIinput\fP [\fIoutput\fP]]

.SH "DESCRIPTION"
.LP 
Apply \fBstylesheet\fR to \fBinput\fR (defaulting to stdin) and write it to the \fBoutput\fR (defaulting to stdout).
.SH "AUTHORS"
.LP 
The Caudium Group \-\- http://caudium.net/
