//  "$Id$";

/* ftp://ftp.ripe.net/iso3166-countrycodes */

constant country_codes = ([ 
  /* Special Top Level Domains */
  "arpa":"Old style Arpanet", 
  "com":"USA Commercial",
  "edu":"USA Educational",
  "gov":"USA Government",
  "int":"International",
  "mil":"USA Military",
  "nato":"NATO",
  "net":"Network",
  "org":"Non-Profit Organisations",

  
  "cs":"Former Czechoslovakia",
  "nt":"Neutral Zone",
  "su":"Former USSR",
 
  "ad":"Andorra",
  "ae":"United Arab Emirates",
  "af":"Afghanistan",
  "ag":"Antigua and Barbuda",
  "ai":"Anguilla",
  "al":"Albania",
  "am":"Armenia",
  "an":"Netherlands Antilles",
  "ao":"Angola",
  "aq":"Antarctica",
  "ar":"Argentina",
  "as":"American Samoa",
  "at":"Austria",
  "au":"Australia",
  "aw":"Aruba",
  "az":"Azerbaijan",
  "ba":"Bosnia and Herzegowina",
  "bb":"Barbados",
  "bd":"Bangladesh",
  "be":"Belgium",
  "bf":"Burkina Faso",
  "bg":"Bulgaria",
  "bh":"Bahrain",
  "bi":"Burundi",
  "bj":"Benin",
  "bm":"Bermuda",
  "bn":"Brunei Darussalam",
  "bo":"Bolivia",
  "br":"Brazil",
  "bs":"Bahamas",
  "bt":"Bhutan",
  "bv":"Bouvet Island",
  "bw":"Botswana",
  "by":"Belarus",
  "bz":"Belize",
  "ca":"Canada",
  "cc":"Cocos (keeling) Islands",
  "cd":"The Democratic Republic Of The Congo",
  "cf":"Central African Republic",
  "cg":"Congo",
  "ch":"Switzerland",
  "ci":"Cote D'ivoire",
  "ck":"Cook Islands",
  "cl":"Chile",
  "cm":"Cameroon",
  "cn":"China",
  "co":"Colombia",
  "cr":"Costa Rica",
  "cu":"Cuba",
  "cv":"Cape Verde",
  "cx":"Christmas Island",
  "cy":"Cyprus",
  "cz":"Czech Republic",
  "de":"Germany",
  "dj":"Djibouti",
  "dk":"Denmark",
  "dm":"Dominica",
  "do":"Dominican Republic",
  "dz":"Algeria",
  "ec":"Ecuador",
  "ee":"Estonia",
  "eg":"Egypt",
  "eh":"Western Sahara",
  "er":"Eritrea",
  "es":"Spain",
  "et":"Ethiopia",
  "fi":"Finland",
  "fj":"Fiji",
  "fk":"Falkland Islands (malvinas)",
  "fm":"Federated States Of Micronesia",
  "fo":"Faroe Islands",
  "fr":"France",
  "fx":"Metropolitan France",
  "ga":"Gabon",
  "gb":"United Kingdom",
  "uk":"United Kingdom",
  "gd":"Grenada",
  "ge":"Georgia",
  "gf":"French Guiana",
  "gh":"Ghana",
  "gi":"Gibraltar",
  "gl":"Greenland",
  "gm":"Gambia",
  "gn":"Guinea",
  "gp":"Guadeloupe",
  "gq":"Equatorial Guinea",
  "gr":"Greece",
  "gs":"South Georgia and The South Sandwich Islands",
  "gt":"Guatemala",
  "gu":"Guam",
  "gw":"Guinea-bissau",
  "gy":"Guyana",
  "hk":"Hong Kong",
  "hm":"Heard and Mc Donald Islands",
  "hn":"Honduras",
  "hr":"Croatia (local Name: Hrvatska)",
  "ht":"Haiti",
  "hu":"Hungary",
  "id":"Indonesia",
  "ie":"Ireland",
  "il":"Israel",
  "in":"India",
  "io":"British Indian Ocean Territory",
  "iq":"Iraq",
  "ir":"Iran (islamic Republic Of)",
  "is":"Iceland",
  "it":"Italy",
  "jm":"Jamaica",
  "jo":"Jordan",
  "jp":"Japan",
  "ke":"Kenya",
  "kg":"Kyrgyzstan",
  "kh":"Cambodia",
  "ki":"Kiribati",
  "km":"Comoros",
  "kn":"Saint Kitts and Nevis",
  "kp":"Democratic People's Republic Of Korea",
  "kr":"Republic Of Korea",
  "kw":"Kuwait",
  "ky":"Cayman Islands",
  "kz":"Kazakhstan",
  "la":"Lao People's Democratic Republic",
  "lb":"Lebanon",
  "lc":"Saint Lucia",
  "li":"Liechtenstein",
  "lk":"Sri Lanka",
  "lr":"Liberia",
  "ls":"Lesotho",
  "lt":"Lithuania",
  "lu":"Luxembourg",
  "lv":"Latvia",
  "ly":"Libyan Arab Jamahiriya",
  "ma":"Morocco",
  "mc":"Monaco",
  "md":"Republic Of Moldova",
  "mg":"Madagascar",
  "mh":"Marshall Islands",
  "mk":"The Former Yugoslav Republic Of Macedonia",
  "ml":"Mali",
  "mm":"Myanmar",
  "mn":"Mongolia",
  "mo":"Macau",
  "mp":"Northern Mariana Islands",
  "mq":"Martinique",
  "mr":"Mauritania",
  "ms":"Montserrat",
  "mt":"Malta",
  "mu":"Mauritius",
  "mv":"Maldives",
  "mw":"Malawi",
  "mx":"Mexico",
  "my":"Malaysia",
  "mz":"Mozambique",
  "na":"Namibia",
  "nc":"New Caledonia",
  "ne":"Niger",
  "nf":"Norfolk Island",
  "ng":"Nigeria",
  "ni":"Nicaragua",
  "nl":"Netherlands",
  "no":"Norway",
  "np":"Nepal",
  "nr":"Nauru",
  "nu":"Niue",
  "nz":"New Zealand",
  "om":"Oman",
  "pa":"Panama",
  "pe":"Peru",
  "pf":"French Polynesia",
  "pg":"Papua New Guinea",
  "ph":"Philippines",
  "pk":"Pakistan",
  "pl":"Poland",
  "pm":"St. Pierre and Miquelon",
  "pn":"Pitcairn",
  "pr":"Puerto Rico",
  "ps":"Palestinian Territory, Occupied",
  "pt":"Portugal",
  "pw":"Palau",
  "py":"Paraguay",
  "qa":"Qatar",
  "re":"Reunion",
  "ro":"Romania",
  "ru":"Russian Federation",
  "rw":"Rwanda",
  "sa":"Saudi Arabia",
  "sb":"Solomon Islands",
  "sc":"Seychelles",
  "sd":"Sudan",
  "se":"Sweden",
  "sg":"Singapore",
  "sh":"St. Helena",
  "si":"Slovenia",
  "sj":"Svalbard and Jan Mayen Islands",
  "sk":"Slovakia (slovak Republic)",
  "sl":"Sierra Leone",
  "sm":"San Marino",
  "sn":"Senegal",
  "so":"Somalia",
  "sr":"Suriname",
  "st":"Sao Tome and Principe",
  "sv":"El Salvador",
  "sy":"Syrian Arab Republic",
  "sz":"Swaziland",
  "tc":"Turks and Caicos Islands",
  "td":"Chad",
  "tf":"French Southern Territories",
  "tg":"Togo",
  "th":"Thailand",
  "tj":"Tajikistan",
  "tk":"Tokelau",
  "tm":"Turkmenistan",
  "tn":"Tunisia",
  "to":"Tonga",
  "tp":"East Timor",
  "tr":"Turkey",
  "tt":"Trinidad and Tobago",
  "tv":"Tuvalu",
  "tw":"Province Of China Taiwan",
  "tz":"United Republic Of Tanzania",
  "ua":"Ukraine",
  "ug":"Uganda",
  "um":"United States Minor Outlying Islands",
  "us":"United States",
  "uy":"Uruguay",
  "uz":"Uzbekistan",
  "va":"Holy See (vatican City State)",
  "vc":"Saint Vincent and The Grenadines",
  "ve":"Venezuela",
  "vg":"Virgin Islands (british)",
  "vi":"Virgin Islands (u.s.)",
  "vn":"Viet Nam",
  "vu":"Vanuatu",
  "wf":"Wallis and Futuna Islands",
  "ws":"Samoa",
  "ye":"Yemen",
  "yt":"Mayotte",
  "yu":"Yugoslavia",
  "za":"South Africa",
  "zm":"Zambia",
  "zr":"Zaire",
  "zw":"Zimbabwe"
 ]);


