.TH "caudiumctl" "1" "1.2.0" "The Caudium Group" "Caudium WebServer"
.SH "NAME"
.LP 
\fBcaudiumctl\fR \- control the \fBCaudium WebServer\fR from command line
.SH "SYNTAX"
.LP 
caudiumctl start|stop|restart|reload
.SH "DESCRIPTION"
.LP 
This program works similarily to the \fIapachectl\fR one \- it enables the user to control
the \fBCaudium WebServer\fR from the command line. One is able to start, stop, restart and reload the configuration of the server.

\fBcaudiumctl\fR supports a config file, placed in /etc/default/caudium which is sourced by
the script if found. The file can contain the following variables.

.TP caudiumhome \- directory (the toplevel one) where Caudium lives.
.TP pidfile \- file containing the PID of the Caudium process.
.TP wwwuser \- user name under which Caudium is supposed to run.
.TP killallwww \- set to 'yes' if you want to kill all the processes owned by $wwwuser.
.TP flags \- the start script flags (see caudium(8) for details)
.SH "OPTIONS"
.LP 
.TP 
\fBstart\fR
Starts the server.
.TP 
\fBstop\fR
Stops the running server.
.TP 
\fBrestart\fR
Restarts a running server.
.TP 
\fBreload\fR
Reloads the configuration of the running server.
.SH "FILES"
.TP /etc/default/caudium \- contains Caudium and caudiumctl default flags
.SH "AUTHORS"
.LP 
The Caudium Group \- \fBhttp://caudium.net/\fR
.SH "SEE ALSO"
.LP 
caudium(8)
