#!/bin/sh -e
#
# $Id$
#
. /usr/share/debconf/confmodule

PORTCHECK='object port = Stdio.Port(); if (!port->bind((int)getenv("PORTNO"))) write("no"); else write("yes");'
PIKE=/usr/bin/pike7

init() {
    db_reset caudium/config_port || true
}

get_cfg_port() {
    local yesno;
    local port;
    
    db_title 'Config Interface Port'
    
    while test 1; do
     db_input high caudium/config_port || true
     db_go
     
     db_get caudium/config_port || true
     if test -z "$RET"; then
      db_reset caudium/config_port || true
      continue
     fi
     
     port="$RET"
     yesno=`env PORTNO=$port $PIKE -e "$PORTCHECK"`
     if test "$yesno" = "no"; then
      db_reset caudium/config_port || true
      db_reset caudium/cfg_port_taken || true
      db_input high caudium/cfg_port_taken || true
      db_go
      continue
     else
      db_subst caudium/last_screen cfgport "$port"
      break
     fi
    done
}

get_iface() {
    local port;
    local yesno;
    
    db_title 'Host address'
    
    while test 1; do
     db_input high caudium/listen_on || true
     db_go
     
     db_get caudium/listen_on
     port="`echo $RET | cut -s -d ':' -f 2`"
     if test -z "$port"; then
        port=80
     fi
     
     yesno=`env PORTNO=$port $PIKE -e "$PORTCHECK"`
     if test "$yesno" = "no"; then
      db_reset caudium/listen_on || true
      db_reset caudium/if_port_taken || true
      db_subst caudium/if_port_taken portno $port
      db_input high caudium/if_port_taken || true
      db_go
      continue
     else
      break
     fi
    done
}

db_version 2.0
db_capb
db_subst caudium/listen_on hostname `hostname -f`

init

if test -f /etc/caudium/servers/localhost; then
    db_title 'Reconfiguration'
    db_input medium caudium/reconfig_localhost || true
    db_go || true
else
    db_set caudium/reconfig_localhost "true"
    RET="true"
fi

if test "$RET" = "true"; then
    db_reset caudium/config_port
    db_reset caudium/start_options
    db_reset caudium/listen_on
    
    get_cfg_port
    get_iface

    db_title 'Startup options'
    
    db_input medium caudium/start_options || true

    db_title 'Caudium configuration'
    db_reset caudium/last_screen
    db_input medium caudium/last_screen || true
    
    db_go || true
fi
#!/bin/sh -e
#
# $Id$
#
. /usr/share/debconf/confmodule

db_version 2.0
db_capb
db_subst caudium/listen_on hostname `hostname -f`

db_title 'Config Interface Port'
db_input medium caudium/config_port || true

db_title 'Host address'
db_input medium caudium/listen_on || true

db_title 'Startup options'
db_input medium caudium/start_options || true

db_go || true
