.TH "pixsl" "1" "1.2.23" "The Caudium Group" "Caudium WebServer"
.SH "NOM"
.LP 
pixsl \- convertis un document suivant la feuille de style XSLT spécifiée.
.SH "SYNTAXE"
.LP 
pixsl <\fIfeuilledestyle\fP> [\fIentrée\fP [\fIsortie\fP]]

.SH "DESCRIPTION"
.LP 
Applique la feuille de style \fBfeuilledestyle\fR à \fBentrée\fR (entrée standard (stdin) par défaut) et écrit le résultat dans \fBsortie\fR (sortie standard (stdout) par défaut).
.SH "AUTEURS"
.LP 
The Caudium Group \-\- http://caudium.net/
